# Generated by Django 3.1.3 on 2020-12-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('cFlag', models.IntegerField(blank=True, null=True)),
                ('sFlag', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=20)),
                ('year', models.IntegerField(default=1900)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('sourceAddress', models.CharField(max_length=50)),
                ('totalValue', models.IntegerField()),
                ('userName', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameOrder', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('collectible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.collectible')),
                ('artist', models.CharField(max_length=50)),
            ],
            bases=('api.collectible',),
        ),
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('collectible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.collectible')),
                ('author', models.CharField(max_length=50)),
                ('illustrator', models.CharField(max_length=50)),
            ],
            bases=('api.collectible',),
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('collectible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.collectible')),
                ('description', models.CharField(max_length=250)),
            ],
            bases=('api.collectible',),
        ),
        migrations.CreateModel(
            name='SportCard',
            fields=[
                ('collectible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.collectible')),
                ('sport', models.CharField(max_length=20)),
            ],
            bases=('api.collectible',),
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionName', models.CharField(max_length=50)),
                ('userName', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameUserCollection', to='api.client')),
            ],
            options={
                'unique_together': {('userName', 'collectionName')},
            },
        ),
        migrations.CreateModel(
            name='Shipping_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingMethod', models.CharField(max_length=50)),
                ('username', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameShipping_Method', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentNo', models.IntegerField(primary_key=True, serialize=False)),
                ('totalValue', models.FloatField()),
                ('formOfPayment', models.CharField(max_length=50)),
                ('orderID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='orderIDPayment', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectible_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collectionIDForms', to='api.collectible')),
                ('collection_name', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collectionNameForms', to='api.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('warehouseNumber', models.IntegerField(default=-1, unique=True)),
                ('username', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameWarehouse', to='api.client')),
            ],
            options={
                'unique_together': {('warehouseNumber', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Wants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionName', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collectionNameWants', to='api.collection')),
                ('userName', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameWants', to='api.client')),
            ],
            options={
                'unique_together': {('userName', 'collectionName')},
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('collectible_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collectionIDSells', to='api.collectible')),
                ('username', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameSells', to='api.client')),
            ],
            options={
                'unique_together': {('collectible_id', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Moderates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUsername', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='adminUsernameModerates', to='api.admin')),
                ('username', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameModerates', to='api.client')),
            ],
            options={
                'unique_together': {('username', 'adminUsername')},
            },
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUsername', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='adminUsernameManages', to='api.admin')),
                ('manage_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collectionIDManage', to='api.collectible')),
            ],
            options={
                'unique_together': {('manage_id', 'adminUsername')},
            },
        ),
        migrations.CreateModel(
            name='Made_Of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectibleIDMadeOf', to='api.collectible')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderIdMadeOf', to='api.order')),
            ],
            options={
                'unique_together': {('collectible_id', 'order_id')},
            },
        ),
        migrations.CreateModel(
            name='Fulfills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingCost', models.FloatField()),
                ('orderID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='orderIDFullfills', to='api.order')),
                ('userName', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usernameFullfills', to='api.client')),
            ],
            options={
                'unique_together': {('userName', 'orderID')},
            },
        ),
        migrations.CreateModel(
            name='Deals_With',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUsername', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='adminUsernameDealsWith', to='api.admin')),
                ('orderID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='orderIDDealsWith', to='api.order')),
            ],
            options={
                'unique_together': {('orderID', 'adminUsername')},
            },
        ),
        migrations.CreateModel(
            name='Consists_Of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionIDConsistsOf', to='api.collectible')),
                ('collectionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionNameConsists_Of', to='api.usercollection')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernameConsists_Of', to='api.usercollection')),
            ],
            options={
                'unique_together': {('username', 'collectible_id', 'collectionName')},
            },
        ),
        migrations.CreateModel(
            name='ComicGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('comicID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.comicbook')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('albumID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.album')),
            ],
        ),
    ]
