# Generated by Django 3.1.3 on 2020-12-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouseNumber',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
    ]
