# Generated by Django 3.1.3 on 2020-12-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumgenre',
            old_name='album',
            new_name='collectible_id',
        ),
    ]
