# Generated by Django 3.1.3 on 2020-12-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201208_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consists_of',
            unique_together={('collectible_id', 'collectionName')},
        ),
        migrations.RemoveField(
            model_name='consists_of',
            name='username',
        ),
    ]
