# Generated by Django 3.1.3 on 2020-12-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201206_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Made_Of',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('sourceAddress', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='collectible_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comicbook',
            old_name='collectible_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='custom',
            old_name='collectible_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sportcard',
            old_name='collectible_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='albumgenre',
            name='collectible_id',
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='albumID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.album'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('address', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('userID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='Wants',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('collectionName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('collectionName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='Shipping_Method',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('shippingMethod', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('ID', models.IntegerField(unique=True)),
                ('collectionName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'ID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentNo', models.IntegerField(primary_key=True, serialize=False)),
                ('formOfPayment', models.CharField(max_length=50)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Moderates',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('adminUserName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('adminUserName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'unique_together': {('ID', 'adminUserName')},
            },
        ),
        migrations.CreateModel(
            name='Fulfills',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'unique_together': {('userID', 'userName')},
            },
        ),
        migrations.CreateModel(
            name='Deals_With',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUserName', models.CharField(max_length=50)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Consists_Of',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('ID', models.IntegerField(unique=True)),
                ('collectionName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'ID')},
            },
        ),
    ]
