# Generated by Django 3.1.3 on 2020-12-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201206_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='userName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
