# Generated by Django 3.1.3 on 2020-12-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201206_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfills',
            name='orderID',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fulfills',
            unique_together={('userID', 'userName', 'orderID')},
        ),
    ]
