# Generated by Django 3.1.3 on 2020-12-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201206_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='comicbook',
            name='year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='custom',
            name='year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='sportcard',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
