from django.urls import path,include
from . import views

urlpatterns = [
    path('clients/', views.ClientList.as_view()),
    path('clients/<int:id>/<str:user>', views.ClientDetail.as_view()),
    path('collectibles/albums/', views.AlbumList.as_view()),
    path('collectibles/albums/<int:pk>', views.AlbumDetail.as_view()),
    path('collectibles/albumsGenre/', views.AlbumGenreList.as_view()),
    path('collectibles/albumsGenre/<int:pk>',
         views.AlbumGenreDetails.as_view()),
    path('collectibles/comicBooks/', views.ComicBookList.as_view()),
    path('collectibles/comicBooks/<int:pk>', views.ComicBookDetails.as_view()),
    path('collectibles/comicGenre', views.ComicgenreList.as_view()),
    path('collectibles/comicGenre/<int:pk>',
         views.ComicGenredetails.as_view()),
    path('collectibles/sportCard', views.SportCardList.as_view()),
    path('collectibles/sportCard/<int:pk>', views.SportCardDetails.as_view()),
    path('collectibles/custom', views.CustomList.as_view()),
    path('collectibles/custom/<int:pk>', views.CustomDetails.as_view()),
    path('collectibles/forms', views.FormsList.as_view()),
    path('collectibles/forms/<int:pk>', views.formsDetails.as_view()),
    path('collectibles/madeOf', views.MadeOfList.as_view()),
    path('collectibles/madeOf/<int:pk>', views.MadeOfDetails.as_view()),
    path('order', views.OrderList.as_view()),
    path('order/<int:pk>', views.OrderListDetails.as_view()),
    path('order/fulfills', views.FulfillsList.as_view()),
    path('order/fulfills/<int:pk>/<str:userName>/<int:orderID>',
         views.FulfillsDetails.as_view()),
    path('payment', views.PaymentList.as_view()),
    path('payment/<int:pk>', views.PaymentDetails.as_view()),
    path('warehouse/', views.WarehouseList.as_view()),
    path('warehouse/<int:id>/<str:user>', views.WarehouseDetail.as_view()),
    path('shipping_method/', views.ShippingMethodList.as_view()),
    path('shipping_method/<int:id>/<str:user>', views.ShippingMethodDetail.as_view()),
    path('moderates/', views.ModeratesList.as_view()),
    path('moderates/<int:id>/<str:user>', views.ModeratesDetail.as_view()),
    path('user_collection/', views.UserCollectionList.as_view()),
    path('user_collection/<int:id>/<str:user>', views.UserCollectionDetail.as_view()),
    path('consists_of/', views.ConsistsOfList.as_view()),
    path('consists_of/<int:id>/<int:userid>', views.ConsistsOfDetail.as_view()),
    path('sells/', views.SellsList.as_view()),
    path('sells/<int:id>/<int:userid>/<str:user>', views.SellsDetail.as_view()),
    path('wants/', views.WantsList.as_view()),
    path('wants/<int:id>/<str:user>', views.WantsDetail.as_view()),
    path('collection/', views.CollectionList.as_view()),
    path('collection/<int:id>', views.CollectionDetail.as_view()),
    path('manages/', views.ManagesList.as_view()),
    path('manages/<int:id>/<str:user>', views.ManagesDetail.as_view()),
    path('api/admin/', views.AdminList.as_view()),
    path('dealswith/', views.DealsWithList.as_view()),
    path('dealswith/<int:id>', views.DealsWithDetail.as_view()),
]